spring.application.name=commerza
server.port=8084
spring.datasource.url=jdbc:postgresql://localhost:5432/commerza
spring.datasource.username=postgres
spring.datasource.password=Deepak123

spring.jpa.hibernate.ddl-auto=create
spring.jpa.shw-sql=true