spring.application.name=commerza
server.port=8084
spring.datasource.url=jdbc:postgresql://localhost:5432/commerza
spring.datasource.username=postgres
spring.datasource.password=Deepak123

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=commerzaservice@gmail.com
spring.mail.password=kktgbeejuhovulwi

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.shw-sql=true

rasorpay.key.id=${RAZORPAY_KEY_ID
rasorpay.key.secert=${RAZORPAY_KEY_SECERT}